[tool.ruff]
target-version = "py313"
line-length = 88

[tool.ruff.lint]
select = [
  "E", "F",
  "I",
  "B",
  "UP",
]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["F401"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.per-file-ignores]
"app/**.py" = ["B008"]